apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapress-front
  namespace: datapress-recette
  labels:
    app: datapress-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapress-front
  template:
    metadata:
      labels:
        app: datapress-front
    spec:
      containers:
        - name: front
          image: datapress-front:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: FRONT_VERSION
              valueFrom:
                configMapKeyRef:
                  name: datapress-config
                  key: FRONT_VERSION
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: datapress-config
                  key: API_BASE_URL
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"
