apiVersion: v1
kind: Secret
metadata:
  name: datapress-secret
  namespace: datapress-recette
type: Opaque
data:
  # "super-secret-token" encod√© en base64
  API_SECRET_TOKEN: c3VwZXItc2VjcmV0LXRva2Vu
